import React, { useState } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Search, Plus, User, MessageSquare, Plus as PlusIcon } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { toast } from 'sonner';

export default function Clients({ data, refresh, navigate }: { data: any, refresh: () => void, navigate: (tab: string) => void }) {
  const [search, setSearch] = useState('');
  const [categoryFilter, setCategoryFilter] = useState('all');
  const [isModalOpen, setIsModalOpen] = useState(false);

  const filteredClients = data.clients.filter((c: any) => {
    const matchesSearch = c.name.toLowerCase().includes(search.toLowerCase()) || 
                         c.phone?.includes(search);
    const matchesCategory = categoryFilter === 'all' || c.category === categoryFilter;
    return matchesSearch && matchesCategory;
  }).sort((a: any, b: any) => a.name.localeCompare(b.name));

  const [selectedClientForMessage, setSelectedClientForMessage] = useState<any>(null);
  const [isMessageModalOpen, setIsMessageModalOpen] = useState(false);

  const sendMessage = (templateType: 'confirmation' | 'reminder' | 'online' | 'rescheduled' | 'cancellation' | 'payment_reminder' | 'payment_received' | 'missed') => {
    if (!selectedClientForMessage) return;
    const phone = selectedClientForMessage.phone.replace(/\D/g, '');
    let text = '';
    
    // Helper to get next/relevant session if available
    const clientAppts = data.appointments.filter((a: any) => a.clientId === selectedClientForMessage.id);
    const nextAppt = clientAppts.find((a: any) => new Date(a.date) >= new Date() && a.status === 'upcoming');
    const lastAppt = [...clientAppts].sort((a: any, b: any) => new Date(b.date).getTime() - new Date(a.date).getTime())[0];
    
    const dateStr = nextAppt ? nextAppt.date : '{{date}}';
    const timeStr = nextAppt ? nextAppt.startTime : '{{time}}';
    const amountStr = lastAppt ? (lastAppt.fee || data.settings.fee) : '{{amount}}';

    switch (templateType) {
      case 'confirmation':
        text = `Hi ${selectedClientForMessage.name},\n\nYour appointment with Dr. ${data.settings.therapistName.split(' ')[0]} has been confirmed for:\n\n🗓 ${dateStr}\n⏰ ${timeStr}\n\nIf you need to reschedule, please reply in advance.\n\nAuto-generated by LUMA OS`;
        break;
      case 'reminder':
        text = `Hi ${selectedClientForMessage.name},\n\nJust a gentle reminder about your appointment today.\n\n⏰ ${timeStr}\n\nLooking forward to seeing you.\n\nAuto-generated by LUMA OS`;
        break;
      case 'online':
        text = `Hi ${selectedClientForMessage.name},\n\nYour appointment begins in approximately 10 minutes.\n\n🔗 ${data.settings.meetingLink || '{{meeting_link}}'}\n\nPlease join a few minutes early if possible.\n\nAuto-generated by LUMA OS`;
        break;
      case 'rescheduled':
        text = `Hi ${selectedClientForMessage.name},\n\nYour appointment has been rescheduled.\n\n🗓 ${dateStr}\n⏰ ${timeStr}\n\nPlease let us know if this timing works for you.\n\nAuto-generated by LUMA OS`;
        break;
      case 'cancellation':
        text = `Hi ${selectedClientForMessage.name},\n\nYour appointment scheduled for ${dateStr} at ${timeStr} has been cancelled.\n\nPlease reach out whenever you’d like to book another appointment.\n\nTake care.\n\nAuto-generated by LUMA OS`;
        break;
      case 'payment_reminder':
        text = `Hi ${selectedClientForMessage.name},\n\nJust a small reminder regarding the pending payment of ₹${amountStr}.\n\nPlease ignore this message if payment has already been made.\n\nThank you.\n\nAuto-generated by LUMA OS`;
        break;
      case 'payment_received':
        text = `Hi ${selectedClientForMessage.name},\n\nPayment of ₹${amountStr} has been received successfully.\n\nThank you.\n\nAuto-generated by LUMA OS`;
        break;
      case 'missed':
        text = `Hi ${selectedClientForMessage.name},\n\nWe noticed today’s appointment was missed.\n\nIf you’d like to reschedule, feel free to reach out anytime.\n\nTake care.\n\nAuto-generated by LUMA OS`;
        break;
    }
    
    window.open(`https://wa.me/${phone}?text=${encodeURIComponent(text)}`, '_blank');
    setIsMessageModalOpen(false);
  };

  const handleAddClient = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const client = {
      name: formData.get('name'),
      phone: formData.get('phone'),
      email: formData.get('email'),
      notes: formData.get('notes'),
      category: formData.get('category') || 'Personal',
    };

    try {
      await fetch('/api/clients', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(client)
      });
      refresh();
      setIsModalOpen(false);
      toast.success('Patient registered');
    } catch (e) {
      toast.error('Registration failed');
    }
  };

  return (
    <div className="space-y-8 pb-32 animate-in fade-in duration-500 text-left">
      <header className="flex justify-between items-center mb-6 px-1">
        <div className="space-y-1">
          <h2 className="text-3xl font-bold tracking-tight text-text-main">Network</h2>
          <p className="text-text-muted text-sm font-medium tracking-tight">Your clinical community</p>
        </div>
        <Dialog open={isModalOpen} onOpenChange={setIsModalOpen}>
          <DialogTrigger className="w-12 h-12 rounded-2xl bg-primary-pink text-white shadow-lg active:scale-90 transition-all flex items-center justify-center">
            <PlusIcon className="w-6 h-6" />
          </DialogTrigger>
          <DialogContent className="sm:max-w-[480px] rounded-[32px] border-border-soft shadow-xl p-8 bg-card overflow-hidden">
            <DialogHeader className="mb-8">
              <DialogTitle className="text-2xl font-bold tracking-tight text-text-main">New Patient</DialogTitle>
            </DialogHeader>
            <form onSubmit={handleAddClient} className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="name" className="text-xs font-semibold uppercase tracking-wider text-text-muted ml-1">Full Name</Label>
                <Input name="name" placeholder="John Doe" required className="rounded-2xl border-border-soft bg-background h-14 px-6 text-text-main font-medium" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="phone" className="text-xs font-semibold uppercase tracking-wider text-text-muted ml-1">Phone Number</Label>
                <Input name="phone" placeholder="+1..." required className="rounded-2xl border-border-soft bg-background h-14 px-6 text-text-main font-medium" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="category" className="text-xs font-semibold uppercase tracking-wider text-text-muted ml-1">Affiliation</Label>
                <Select name="category" defaultValue="Personal">
                  <SelectTrigger className="rounded-2xl border-border-soft bg-background h-14 px-6 text-text-main font-medium">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent className="rounded-2xl border-border-soft bg-card">
                    <SelectItem value="Personal" className="text-text-main">Personal</SelectItem>
                    <SelectItem value="Clinic" className="text-text-main">Clinic</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <Button type="submit" className="w-full rounded-2xl h-14 bg-primary-sage text-white font-semibold shadow-md active:scale-95 transition-all mt-4">
                Register Patient
              </Button>
            </form>
          </DialogContent>
        </Dialog>
      </header>

      <div className="relative group">
        <Search className="absolute left-6 top-1/2 -translate-y-1/2 w-5 h-5 text-text-muted opacity-50 pointer-events-none group-focus-within:text-primary-sage transition-colors" />
        <Input 
          placeholder="Search by name or phone..." 
          className="pl-14 h-16 rounded-[24px] border-none shadow-sm bg-card text-lg font-medium placeholder:text-text-muted focus-visible:ring-primary-sage/20 transition-all text-text-main"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </div>

      <div className="flex gap-3 overflow-x-auto pb-2 hide-scrollbar">
        {['all', 'Personal', 'Clinic'].map((type) => (
          <button
            key={type}
            onClick={() => setCategoryFilter(type)}
            className={`px-6 py-2.5 rounded-full text-sm font-semibold tracking-tight transition-all duration-300 border ${
              categoryFilter === type 
                ? 'bg-primary-pink text-white border-primary-pink shadow-md' 
                : 'bg-card text-text-muted border-border-soft hover:bg-background'
            }`}
          >
            {type.charAt(0).toUpperCase() + type.slice(1)}
          </button>
        ))}
      </div>

      <div className="space-y-4">
        {filteredClients.map((client: any) => (
          <Card key={client.id} className="border-none shadow-sm bg-card rounded-3xl p-6 group active:scale-[0.99] transition-all duration-300">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-5">
                <div className="w-14 h-14 rounded-2xl bg-background flex items-center justify-center text-text-muted group-hover:bg-primary-sage/10 group-hover:text-primary-sage transition-all duration-500">
                  <User className="w-6 h-6" />
                </div>
                <div className="space-y-0.5">
                  <h3 className="text-xl font-bold text-text-main tracking-tight leading-tight">{client.name}</h3>
                  <div className="flex items-center gap-2">
                    <p className="text-sm font-medium text-text-muted opacity-80 tracking-tight">{client.phone}</p>
                    {client.category === 'Clinic' && (
                       <span className="text-[10px] bg-primary-sage/10 text-primary-sage px-2 py-0.5 rounded-md font-bold uppercase tracking-wider">Clinic</span>
                    )}
                  </div>
                </div>
              </div>
              
              <div className="flex gap-2">
                <button 
                  onClick={() => {
                    setSelectedClientForMessage(client);
                    setIsMessageModalOpen(true);
                  }}
                  className="w-12 h-12 rounded-2xl bg-background text-text-muted flex items-center justify-center hover:bg-primary-sage/10 hover:text-primary-sage transition-all"
                >
                  <MessageSquare className="w-5 h-5" />
                </button>
                <button 
                  onClick={() => {
                    navigate('calendar');
                    toast.info(`Scheduling ${client.name}`);
                  }}
                  className="w-12 h-12 rounded-2xl bg-primary-sage text-white flex items-center justify-center shadow-md active:scale-90 transition-all"
                >
                  <Plus className="w-6 h-6" />
                </button>
              </div>
            </div>
          </Card>
        ))}
      </div>

      <Dialog open={isMessageModalOpen} onOpenChange={setIsMessageModalOpen}>
        <DialogContent className="sm:max-w-[400px] rounded-[32px] border-border-soft shadow-xl p-8 bg-card overflow-hidden text-left">
          <DialogHeader className="mb-6">
            <DialogTitle className="text-xl font-bold tracking-tight text-text-main">Draft Message</DialogTitle>
            <p className="text-xs font-semibold text-text-muted uppercase tracking-wider">For {selectedClientForMessage?.name}</p>
          </DialogHeader>
          
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <Button 
              variant="outline" 
              onClick={() => sendMessage('confirmation')}
              className="justify-start h-14 rounded-2xl border-border-soft hover:bg-background text-text-main font-medium px-4 text-xs"
            >
              Confirmation
            </Button>
            <Button 
              variant="outline" 
              onClick={() => sendMessage('reminder')}
              className="justify-start h-14 rounded-2xl border-border-soft hover:bg-background text-text-main font-medium px-4 text-xs"
            >
              Reminder
            </Button>
            <Button 
              variant="outline" 
              onClick={() => sendMessage('online')}
              className="justify-start h-14 rounded-2xl border-border-soft hover:bg-background text-text-main font-medium px-4 text-xs"
            >
              Online Link
            </Button>
            <Button 
              variant="outline" 
              onClick={() => sendMessage('rescheduled')}
              className="justify-start h-14 rounded-2xl border-border-soft hover:bg-background text-text-main font-medium px-4 text-xs"
            >
              Rescheduled
            </Button>
            <Button 
              variant="outline" 
              onClick={() => sendMessage('cancellation')}
              className="justify-start h-14 rounded-2xl border-border-soft hover:bg-background text-text-main font-medium px-4 text-xs"
            >
              Cancellation
            </Button>
            <Button 
              variant="outline" 
              onClick={() => sendMessage('payment_reminder')}
              className="justify-start h-14 rounded-2xl border-border-soft hover:bg-background text-text-main font-medium px-4 text-xs"
            >
              Pay Reminder
            </Button>
            <Button 
              variant="outline" 
              onClick={() => sendMessage('payment_received')}
              className="justify-start h-14 rounded-2xl border-border-soft hover:bg-background text-text-main font-medium px-4 text-xs"
            >
              Pay Received
            </Button>
            <Button 
              variant="outline" 
              onClick={() => sendMessage('missed')}
              className="justify-start h-14 rounded-2xl border-border-soft hover:bg-background text-text-main font-medium px-4 text-xs"
            >
              Missed Session
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {filteredClients.length === 0 && (
        <div className="flex flex-col items-center justify-center py-20 text-stone-300">
           <Search className="w-10 h-10 mb-4 opacity-20" />
           <p className="text-lg font-semibold text-text-muted opacity-50">No patients found</p>
        </div>
      )}
    </div>
  );
}
